// import Image from 'next/image'
// import { Html, Head, Main, NextScript } from 'next/document'
// import Cartoon from '../src/assets/images/cartoon.svg'
// import Logo from '../src/assets/logo/plotly-logo.svg'
// import Graph1 from '../src/assets/images/dark-graph.svg'
// import Graph2 from '../src/assets/images/light-graph.svg'
// import Man from '../src/assets/images/man.svg'
// import Social from '../src/assets/logo/socials.svg'


// export default function Home() {
//   return (


//     // <Html className="container" style={{ backgroundColor: '#F0F2FF', padding: '4rem 2rem' }}>
//     //   <Head>
//     //     <title>Plotly - Email</title>
//     //     <meta name="description" content="Generated by create next app" />
//     //     <link rel="icon" href="/favicon.ico" />
//     //     <style global jsx> {`
//     //         html,
//     //         body {
//     //           padding: 0;
//     //           margin: 0;
//     //           font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
//     //           Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
//     //         }

//     //         * {
//     //           box-sizing: border-box;
//     //           }

//     //         @media (prefers-color-scheme: dark) {
//     //           html {
//     //             color-scheme: dark;
//     //           }

//     //           body {
//     //             color: white;
//     //             background: black;
//     //           }
//     //     `}
//     //     </style>
//     //   </Head>
//     //   <div style={{ m: 'auto', display: 'block' }}>
//     //     <Image src={Logo} alt="plotly-logo" />
//     //   </div>

//     //   <main className="main">

//     //     <style jsx> {`
//     //       main {
//     //         margin: 0;
//     //         background-color: white;
//     //         border-radius: 11px;
//     //         padding: 2rem 1.5rem;
//     //       }
//     //       table {
//     //         border - spacing: 0;
//     //       }
//     //       td {
//     //         padding: 0;
//     //       }
//     //       img {
//     //         border: 0;
//     //       }
//     //       .row--one {
//     //         background-color: yellow;
//     //       }

//     //       .row--two {
//     //         background-color: pink;
//     //       }

//     //       .cartoon {
//     //         margin: auto;
//     //         display: block;
//     //       }

//     //       .title {
//     //         font-size: 1rem;
//     //         color: #1E1E1E;

//     //       }

//     //       .subtitle, .subtitle__two {
//     //         font-size: 0.8rem;
//     //         color: #7E8489;
//     //         font-weight: 400;
//     //       }

//     //       .subtitle {
//     //         font-weight: 600;
//     //       }

//     //       .graphs {
//     //         display: flex;
//     //         flex-direction: row;
//     //       }
//     //     `}
//     //     </style>

//     //     <div>
//     //       <table>
//     //         <tr>

//     //           <div className="row--one" >
//     //             <td style={{ borderBottom: '1px solid #e7e7e7' }}>
//     //               <table>
//     //                 <tr>
//     //                   <td>
//     //                     <div className="cartoon" >
//     //                       <Image src={Cartoon} alt='cartoon-pic' />
//     //                     </div>
//     //                   </td>
//     //                 </tr>
//     //                 <tr>
//     //                   <th style={{ textAlign: 'left' }} >
//     //                     <h1 className="title" >Dash Club -2022 Edition </h1>
//     //                   </th>
//     //                 </tr>
//     //                 <tr>
//     //                   <td>
//     //                     <h2 className="subtitle" >
//     //                       Hello Dash Club and Happy 2020!
//     //                     </h2>
//     //                   </td>
//     //                 </tr>
//     //                 <tr>
//     //                   <td>
//     //                     <h3 className="subtitle__two" >
//     //                       It has been a while, and we've got lots of good stuff from the last few months to share.
//     //                     </h3>
//     //                   </td>
//     //                 </tr>
//     //               </table>
//     //             </td>
//     //           </div>


//     //           <tr>
//     //             <div className="row--two">
//     //               <td>
//     //                 <table>
//     //                   <tr>
//     //                     <td>
//     //                       <p>
//     //                         We spent the fall working on page load performance:

//     //                       </p>
//     //                     </td>
//     //                   </tr>
//     //                   <tr>
//     //                     <td>
//     //                       <p>
//     //                         1. Previously, we loaded all of the JavaScript from all of the component librar- ies upfront. Now, we load them on demand. This is called “lazy loading.” So, if your home page doesn't display a graph, then the plotly.js library isn't loaded until you navigate to the page that does.

//     //                       </p>
//     //                     </td>
//     //                   </tr>
//     //                   <tr>
//     //                     <td>
//     //                       <p>
//     //                         2. We started caching your app’s JavaScript and CSS assets.

//     //                       </p>
//     //                     </td>
//     //                   </tr>
//     //                   <tr>
//     //                     <td>
//     //                       <p>
//     //                         With these improvements, our documentation (https://dash.plot.ly) loads much, much faster. Your apps should too!
//     //                       </p>
//     //                     </td>
//     //                   </tr>
//     //                 </table>

//     //                 <tr >
//     //                   <td   >
//     //                     <table >

//     //                       <tr>
//     //                         <td  >
//     //                           <Image src={Graph1} alt='dark-graph' ></Image>
//     //                         </td>
//     //                         <td >
//     //                           <Image src={Graph2} alt='light-graph'  ></Image>
//     //                         </td>
//     //                       </tr>

//     //                       <tr >
//     //                         <td >
//     //                           <h3  >Lorem ipsum text</h3>
//     //                         </td>
//     //                         <td  >
//     //                           <h3 >Lorem ipsum text</h3>
//     //                         </td>
//     //                       </tr>

//     //                       <tr >
//     //                         <td >
//     //                           <p  >
//     //                             Lorem ipsum dolor sit amet, consecte- tur adipiscing elit, sed do eiusmod tempor.
//     //                           </p>
//     //                         </td>
//     //                         <td >
//     //                           <p  >
//     //                             Lorem ipsum dolor sit amet, consecte- tur adipiscing elit, sed do eiusmod tempor.
//     //                           </p>
//     //                         </td>
//     //                       </tr>

//     //                       <tr>
//     //                         <td >
//     //                           <button className="button">
//     //                             Read More
//     //                           </button>
//     //                         </td>
//     //                         <td >
//     //                           <button className="button">
//     //                             Read More
//     //                           </button>
//     //                         </td>
//     //                       </tr>
//     //                     </table>
//     //                   </td>
//     //                 </tr>
//     //               </td>
//     //             </div>
//     //           </tr>

//     //           {/* man 1 section */}

//     //           <tr>
//     //             <td >
//     //               <table>
//     //                 <tr>
//     //                   <td rowSpan='3'>
//     //                     <Image src={Man} alt='man-profile'   ></Image>
//     //                   </td>
//     //                   <td >
//     //                     <h3 >
//     //                       Lorem ipsum text
//     //                     </h3>
//     //                   </td>
//     //                 </tr>

//     //                 <tr>
//     //                   <td >
//     //                     <p>
//     //                       Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidi- dunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
//     //                     </p>
//     //                   </td>
//     //                 </tr>

//     //                 <tr>
//     //                   <td >
//     //                     <button className="button" >
//     //                       Read More
//     //                     </button>
//     //                   </td>
//     //                 </tr>
//     //               </table>
//     //             </td>
//     //           </tr>

//     //           {/* man 2 */}

//     //           <tr>
//     //             <td >
//     //               <table>
//     //                 <tr>
//     //                   <td >
//     //                     <h3 >
//     //                       Lorem ipsum text
//     //                     </h3>
//     //                   </td>
//     //                   <td rowSpan='3' >
//     //                     <Image src={Man} alt='man-profile'   ></Image>
//     //                   </td>
//     //                 </tr>

//     //                 <tr>
//     //                   <td >
//     //                     <p >
//     //                       Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidi- dunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
//     //                     </p>
//     //                   </td>
//     //                 </tr>
//     //                 <tr>
//     //                   <td >
//     //                     <button >
//     //                       Read More
//     //                     </button>
//     //                   </td>
//     //                 </tr>
//     //               </table>
//     //             </td>
//     //           </tr>







//     //         </tr>
//     //       </table>
//     //     </div>

//     //   </main >

//     //   <footer >
//     //     <tr>
//     //       <td p={{ base: '0rem', md: '1rem 0 0 2rem' }} border='none'>
//     //         <table>
//     //           <tr>
//     //             <td border='none' p={{ base: '1rem 0 1rem', sm: '1.5rem 0 1rem', md: '2rem 0 1rem', lg: '2rem 0 1rem 1rem' }} >
//     //               <Image src={Social} alt='socials-logo' ></Image>
//     //             </td>
//     //           </tr>
//     //           <tr>
//     //             <td border='none' p={{ base: '0', md: '0 0 0.2rem 0', lg: '0 0 0.2rem 1rem' }} >
//     //               <p fontSize={{ base: '2xs', sm: 'xs', md: 'sm', lg: 'md' }} color='#7E8489'>Ⓒ 2022 Plotly. All rights reserved.</p>
//     //             </td>
//     //           </tr>
//     //           <tr>
//     //             <td border='none' p={{ base: '0', lg: '0 0 0 1rem' }} lineHeight={{ base: '10px', lg: '18px' }}>
//     //               <p >Click <span> HERE </span>  to unsubscribe or change your email preferences.</p>
//     //             </td>
//     //           </tr>
//     //         </table>
//     //       </td>
//     //     </tr>
//     //   </footer>
//     // </Html >
//   )
// }
